services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    command: npm run start:debug
    ports:
      - "3001:3000"
      - "9229:9229" # Node.js debug port
    volumes:
      - ./backend/src:/app/src
      - ./backend/dist:/app/dist
      - backend_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      FRONTEND_URL: "http://localhost:5173"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    command: npm run dev -- --host
    volumes:
      - ./frontend/src:/app/src
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3001"

volumes:
  backend_node_modules:
  frontend_node_modules:
